apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          name: node-app
          image: googlesolution.azurecr.io/node-app

--- 

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - port: 8080
      targetPort: 8080